name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-2_2_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the 2.2.0 Docker image
      run: docker build 2.2.0/. --tag my-image-name:$(date +%s)
